spring.application.name=persistence-worker

# ============================================================
# 1. Credenciais Fake para o LocalStack
# ============================================================
spring.cloud.aws.credentials.access-key=test
spring.cloud.aws.credentials.secret-key=test

# ============================================================
# 2. Região AWS
# ============================================================
spring.cloud.aws.region.static=us-east-1

# ============================================================
# 3. Endpoint LocalStack (SQS)
# ============================================================
spring.cloud.aws.endpoint=http://localhost:4566
spring.cloud.aws.sqs.endpoint=http://localhost:4566

# ============================================================
# 4. Filas SQS
# fila de entrada: notas validadas pelo validation-worker
# fila de saída:  monitor de eventos
# ============================================================
persistence.sqs.input-queue-name=notas-processadas
persistence.sqs.monitor-queue-url=http://localhost:4566/000000000000/fila-monitor

# ============================================================
# 5. S3 (LocalStack)
# ============================================================
persistence.s3.bucket-name=notas-fiscais-bucket
persistence.s3.endpoint=http://localhost:4566

# ============================================================
# 6. PostgreSQL
# ============================================================
spring.datasource.url=jdbc:postgresql://localhost:5432/asyncflow
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# ============================================================
# 7. JPA / Hibernate
# ============================================================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true

# ============================================================
# 8. Porta do servidor
# ============================================================
server.port=8082

# ============================================================
# 9. Logs
# ============================================================
logging.level.io.awspring.cloud.sqs=DEBUG
logging.level.com.example.AsyncFlow=INFO
