services:
  localstack:
    image: localstack/localstack:3.4.0  # Versão estável que não exige token
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs,s3
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: asyncflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d asyncflow"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: