spring.application.name=validation-worker

# 1. Credenciais Fake para o LocalStack
spring.cloud.aws.credentials.access-key=test
spring.cloud.aws.credentials.secret-key=test

# 2. Região (deve ser a mesma do docker-compose e do terminal)
spring.cloud.aws.region.static=us-east-1

# 3. Redirecionando para o LocalStack (Porta 4566)
spring.cloud.aws.endpoint=http://localhost:4566

# 4. Configuração específica do SQS
spring.cloud.aws.sqs.endpoint=http://localhost:4566

# 5. Nome da nossa fila
projeto.sqs.queue-name=validacao-vendas

# Opcional: Logs para você ver o que está acontecendo
logging.level.io.awspring.cloud.sqs=DEBUG

# Porta do servidor
server.port=8081

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/asyncflow
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
